spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/fitness-micro-user
    username: Basharat
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
